/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.GameNotifier;
import Model.Language;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;

/**
 *
 * @author dave
 */
public class BoggleFrame extends javax.swing.JFrame {

    private Container contentPane;
    private MainSound sounds;
    private BoardPanel board;
    private GameNotifier notifier;

    /**
     * Creates new form BoggleFrameForm
     *
     * @param rows
     * @param ids
     * @param notifier
     */
    public BoggleFrame(int rows, String[] ids, GameNotifier notifier) {
        super("Boggle!");
        try {
            for (LookAndFeelInfo info
                    : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }

            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        } catch (Exception e) {
            e.printStackTrace();
        }

        initComponents();
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                setVisible(false);
                board.t.stop();
                dispose();
            }
        });

        this.notifier = notifier;
        contentPane = getContentPane();
        sounds = new MainSound();
        initPanels(ids, rows);

        this.setLocationRelativeTo(null);
        pack();
        setVisible(true);

    }

    public void refreshIds(ArrayList<Integer> ids) {
        board.highlightIds(ids, Color.YELLOW);
    }

    private void initPanels(String[] ids, int rows) {
        board = new BoardPanel(ids, sounds, rows, notifier);
        contentPane.add(board, BorderLayout.CENTER);
    }

    public void clearBoard() {
        board.clear();
        wordEnteredField.setText("");
    }

    public void resetBoard(String[] ids) {
        board.resetBoardText(ids);
        clearBoard();
    }

    public void highlightIds(ArrayList<Integer> ids) {
        board.highlightIds(ids, Color.YELLOW);
    }

    public void correctWord(String s, int newPoints) {
        board.highlightSelected(Color.GREEN);
        wordEnteredField.setText("");
        pointsField.setText(newPoints + "");
    }

    public void incorrectWord() {
        board.highlightSelected(Color.RED);
        wordEnteredField.setText("");
    }

    public String getTypedWord() {
        return this.wordEnteredField.getText();
    }
    public void setTypedWord(String s){
        wordEnteredField.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentWordPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        wordEnteredField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pointsField = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Word:");

        wordEnteredField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordEnteredFieldActionPerformed(evt);
            }
        });
        wordEnteredField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                wordEnteredFieldKeyReleased(evt);
            }
        });

        jLabel2.setText("Points:");

        pointsField.setText("0");

        javax.swing.GroupLayout currentWordPanelLayout = new javax.swing.GroupLayout(currentWordPanel);
        currentWordPanel.setLayout(currentWordPanelLayout);
        currentWordPanelLayout.setHorizontalGroup(
            currentWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentWordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wordEnteredField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pointsField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        currentWordPanelLayout.setVerticalGroup(
            currentWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentWordPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(currentWordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(wordEnteredField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(pointsField))
                .addGap(1, 1, 1))
        );

        getContentPane().add(currentWordPanel, java.awt.BorderLayout.PAGE_END);

        jMenu1.setText("Game");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Shuffle");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Game Mode");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Language");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Set Language");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Language[] options = Language.values();
        Language l = (Language) JOptionPane.showInputDialog(
                this,
                "",
                "Choose Language",
                JOptionPane.PLAIN_MESSAGE,
                null,
                options,
                notifier.getCurrLang().toString().toLowerCase());

        if (l != null) {
            notifier.setLang(l);
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    //shuffle
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        notifier.newPuzzle();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    //game modes
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        //todo
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    //word entered
    private void wordEnteredFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordEnteredFieldActionPerformed
        notifier.enterPushed();

    }//GEN-LAST:event_wordEnteredFieldActionPerformed

    private void wordEnteredFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wordEnteredFieldKeyReleased
        notifier.wordFieldUpdated(wordEnteredField.getText());

    }//GEN-LAST:event_wordEnteredFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel currentWordPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel pointsField;
    private javax.swing.JTextField wordEnteredField;
    // End of variables declaration//GEN-END:variables

}
